server:
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
logging:
  file:
    path: /var/log/my-klas
  level:
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: fatal
    org.hibernate.SQL: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
    tags:
      application: "my-klas"
    export:
      prometheus:
        pushgateway:
          enabled: true
          push-rate: 1s
domain:
  constraints:
    max-credit: 19
    max-grade-for-retaking: C_PLUS
