global:
  scrape_interval: 1s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
- job_name: pushgateway
  honor_labels: true
  static_configs:
  - targets: ['localhost:9091']
- job_name: 'mysqld_exporter'
  static_configs:
  - targets: ['localhost:9104']
- job_name: 'node_exporter'
  static_configs:
  - targets: ['localhost:9100']
